#
# ~/.bashrc
#

# basic
alias c='clear'
alias t='tree -Ca'
alias l='ls -CFa'
alias ll='ls -alFNA --si'
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias rm='trash-put'
alias sqlite='sqlite3'

# editors
alias vim='nvim'
alias v='nvim'
alias e='emacsclient -n -c'

# misc
alias torrent='rtorrent'
alias doze='systemctl suspend'
alias font='cd /usr/local/share/fonts'

# apps
alias filen='app /home/chenel/Applications/filen_x86_64.AppImage'
alias zotero='app zotero'
alias vlc='app /usr/bin/vlc'
alias anki='app anki'
alias obsidian='app obsidian'
alias firefox='app firefox'
alias aw='app aw-qt'
alias foliate='app foliate'
alias okular='app okular'
alias proton-pass='app proton-pass'

alias ical='app snap run icloud-for-linux.calendar'
alias inotes='app snap run icloud-for-linux.notes'
alias icloud='app snap run icloud-for-linux.drive'
alias ifind='app snap run icloud-for-linux.find-my-iphone'
alias imail='app snap run icloud-for-linux.mail'
alias iphotos='app snap run icloud-for-linux.photos'

app() {
  eval "$1" "'${@:2}'" &>/dev/null &
}

doc() {
	zathura "$1" &>/dev/null &
}

PROMPT_COMMAND=${PROMPT_COMMAND:+$PROMPT_COMMAND; }'disown -a -h'
TERM="screen-256color"
PS1='[\u@\h \W]$ '

export VISUAL=vim
export HISTTIMEFORMAT="%m/%d/%y %T "
export HISTSIZE=100000

export PATH="$PATH:/home/chenel/.local/bin:/usr/local/texlive/2023/bin/x86_64-linux:/home/chenel/.config/emacs/bin:/home/chenel/Applications"

export XDG_DATA_HOME=~/.local/share
export XDG_CONFIG_HOME=~/.config
